export enum CodigoRol {
  PERSONAL_PASTORAL = "PERSONAL_PASTORAL",
  COORDINADOR_PARROQUIAL = "COORDINADOR_PARROQUIAL",
  COORDINADOR_VICARIAL = "COORDINADOR_VICARIAL",
  COORDINADOR_DIOCESANO = "COORDINADOR_DIOCESANO",
  ADMINISTRADOR = "ADMINISTRADOR",
}

export enum EstadoSolicitud {
  BORRADOR = "BORRADOR",
  PRESENTADA = "PRESENTADA",
  EN_REVISION = "EN_REVISION",
  APROBADA = "APROBADA",
  ACTIVA = "ACTIVA",
  RECHAZADA = "RECHAZADA",
  FINALIZADA = "FINALIZADA",
  CANCELADA = "CANCELADA",
}

export enum DecisionPlanAyuda {
  APROBADA = "APROBADA",
  RECHAZADA = "RECHAZADA",
}

export enum TipoActorAuditoria {
  USUARIO = "USUARIO",
  SISTEMA = "SISTEMA",
  TAREA_AUTOMATICA = "TAREA_AUTOMATICA",
}

export enum ResultadoAuditoria {
  EXITOSO = "EXITOSO",
  FALLIDO = "FALLIDO",
}

export enum OrigenAuditoria {
  APLICACION = "APLICACION",
  API = "API",
  TAREA_PROGRAMADA = "TAREA_PROGRAMADA",
  CONSOLA_ADMINISTRATIVA = "CONSOLA_ADMINISTRATIVA",
}

export enum FrecuenciaEntrega {
  UNICA = "UNICA",
  SEMANAL = "SEMANAL",
  QUINCENAL = "QUINCENAL",
  MENSUAL = "MENSUAL",
  BIMESTRAL = "BIMESTRAL",
  TRIMESTRAL = "TRIMESTRAL",
  SEGUN_NECESIDAD = "SEGUN_NECESIDAD",
}

export enum AccionAuditoria {
  INICIAR_SESION = "INICIAR_SESION",
  CERRAR_SESION = "CERRAR_SESION",
  FALLAR_INICIO_SESION = "FALLAR_INICIO_SESION",
  CONSULTAR_EXPEDIENTE = "CONSULTAR_EXPEDIENTE",
  BUSCAR_PERSONA = "BUSCAR_PERSONA",
  CREAR = "CREAR",
  ACTUALIZAR = "ACTUALIZAR",
  ELIMINAR_LOGICAMENTE = "ELIMINAR_LOGICAMENTE",
  RESTAURAR = "RESTAURAR",
  CAMBIAR_ESTADO_SOLICITUD = "CAMBIAR_ESTADO_SOLICITUD",
  APROBAR_AYUDA = "APROBAR_AYUDA",
  RECHAZAR_AYUDA = "RECHAZAR_AYUDA",
  REGISTRAR_ENTREGA = "REGISTRAR_ENTREGA",
  CREAR_USUARIO = "CREAR_USUARIO",
  CAMBIAR_ROL = "CAMBIAR_ROL",
  CAMBIAR_ALCANCE = "CAMBIAR_ALCANCE",
  DESACTIVAR_USUARIO = "DESACTIVAR_USUARIO",
  CARGAR_DOCUMENTO = "CARGAR_DOCUMENTO",
  VISUALIZAR_DOCUMENTO = "VISUALIZAR_DOCUMENTO",
  DESCARGAR_DOCUMENTO = "DESCARGAR_DOCUMENTO",
  EXPORTAR_DATOS = "EXPORTAR_DATOS",
}

export const ESTADOS_SOLICITUD_VIGENTES: EstadoSolicitud[] = [
  EstadoSolicitud.PRESENTADA,
  EstadoSolicitud.EN_REVISION,
  EstadoSolicitud.APROBADA,
  EstadoSolicitud.ACTIVA,
];
